apiVersion: v1
kind: Pod
metadata:
  name: linux
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    resources:
      limits:
        cpu: "100m"
        memory: "10Mi"