apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8800 # ข้างนอกเข้ามา Expose the service on internal port 8800
    targetPort: 80 # ภายใน Forward traffic to port 80 on the pods
    protocol: TCP # โปรโตคอลที่ใช้ในการสื่อสาร
  selector:
    app: nginx