apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: demok8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: iamsamitdev/mern_nodejs:1.0
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_USER
          value: "admin"
        - name: DATABASE_PASSWORD
          value: "1234"
        - name: DATABASE_HOST
          value: "mongodb-service" # Service name of MongoDB
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: demok8s
spec:
  selector:
    app: nodejs
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001

